CREATE TABLE [dbo].[Brand] (
    [BrandId]   INT            IDENTITY (1, 1) NOT NULL,
    [BrandName] NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([BrandId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

