CREATE TABLE [dbo].[ProductColor] (
    [ProductColorId]   INT            IDENTITY (1, 1) NOT NULL,
    [ProductColorName] NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([ProductColorId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

