CREATE TABLE [dbo].[ProductSize] (
    [ProductSizeId]   INT            IDENTITY (1, 1) NOT NULL,
    [ProductSizeName] NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([ProductSizeId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

