CREATE TABLE [dbo].[TradeKinds] (
    [TraderKindId]   INT            IDENTITY (1, 1) NOT NULL,
    [TraderKindName] NVARCHAR (128) NOT NULL,
    [Description]    NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([TraderKindId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

